In [5]:
import os
import matplotlib.pyplot as plt
import joblib # save model as binary
import numpy as np
import pandas as pd

plt.style.use('fivethirtyeight')  # for matpltlib styles

In [3]:
class Perceptron:
    def __init__(self,eta:float=None,epochs:int=None):
        self.weights =np.random.randn(3) * 1e-4
        self.eta =eta # learnig rata
        self.epochs = epochs # iterations
        
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights)
    
    def activation_function(self,z):
        return np.where(z>0, 1, 0)
        
    def fit(self, X,y):
        self.X =X
        self.y =y
        
        #X_with_bias = np.c_[self.X,-np.ones(4,1)]
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f'X with the bias:\n{X_with_bias}')
        
        for epoch in range(self.epochs):
            z =self._z_outcome(X_with_bias, self.weights)

            y_hat =self.activation_funcation(z)
            
            self.error =self.y - y_hat
            
            #weight update rule
            self.weights = self.weights +self.eta *np.dot(X_with_bias.T,self.error)
            
        def predict(self,X):
            X_with_bias =np.c_[X,-np.ones(len(X), 1)]
            z =self._z_outcome(X_with_bias, self.weights)
            return self.activaton_function
        
        

In [6]:
OR ={
    
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y': [0,1,1,1]
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [10]:
def prepare_data(df,target_col ='y'):
    X =df.drop(target_col,axis =1)
    y = df[target_col]
    
    return X, y

In [11]:
X,y = prepare_data(df_OR)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [12]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [35]:
obj =Perceptron(eta =0.01,epochs =10)


In [36]:
obj.epochs

10

In [37]:
obj.weights

array([-2.06952798e-05,  8.76000934e-05,  9.58619480e-05])

In [38]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
y = np.ones((4,1))


In [40]:
obj.fit(X, y)

X with the bias:
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [43]:
z=-34
np.where(z>0, 1, 0)

array(0)